version: "3"

networks:
  loki:

x-logging: &log
  driver: "json-file"
  options:
    max-size: "64m"
    max-file: "2"
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:
  python_app:
    image: dshamik/dshamik_msk_time:latest
    container_name: python_app
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      <<: *log
    ports:
      - "8000:8090"

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      <<: *log

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./configs/promtail:/etc/promtail/configs
    command: -config.file=/etc/promtail/configs/promtail.yaml
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      <<: *log

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      <<: *log

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 512m
    logging:
      <<: *log
    ports:
      - "9090:9090"