global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:

  - job_name: loki
    honor_timestamps: true
    scrape_interval: 5s
    static_configs:
      - targets:
          - loki:3100

  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090