---
 - name: Update apt cache
   apt:
     update_cache: yes

 - name: Install Docker dependencies
   apt:
     name: "{{ docker_dependencies }}"
     update_cache: yes

 - name: Add Docker apt key
   apt_key:
     url: "{{ docker_apt_key }}"

 - name: Add Docker repository
   apt_repository:
     repo: "{{ doker_repo }}"

 - name: Install Docker
   apt:
     name: "{{ docker_packages }}"
     state: "{{ docker_packages_state }}